#!/bin/bash

ADDRESS="${ADDRESS:-localhost}"

openssl genrsa -out server.key 2048

openssl req -new -x509 -sha256 -key server.key -out server.crt -days 3650 -subj "/C=EU/ST=Germany/L=Franconia/O=Quarks/CN=${ADDRESS}"