name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.1]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: make test
    - name: Build
      run: make build
    - name: Smoke
      run: |
            make run &
            sleep 5
            make smoke-test
